[package]
name = "hello_rust"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "tp1"
path = "src/tp1.rs"

[[bin]]
name = "tp2"
path = "src/tp2.rs"

[[bin]]
name = "tp3"
path = "src/tp_gestionnaire_fichiers.rs"

[dependencies]
chrono = "0.4"
